//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int logId { get; set; }
        public string userId { get; set; }
        public System.DateTime actionDate { get; set; }
        public string location { get; set; }
        public string page { get; set; }
        public string action { get; set; }
        public string result { get; set; }
    }
}
